### ISSUE TITLE
T3 v1.6

### ISSUE THREAD

**Issue by M0IGA** [SQ9MDD/TTGO-T-Beam-LoRa-APRS#20]
Proszę by dodać kolejny konfig dla T3 v1.6 i zdecydować się jaki pin ma robić za user button, sprawdzić czy diody są tam gdzie mają być.

(Wpisałem to co mówił Łukasz na temat modułu T3)

**Comment by SQ9MDD** [comment]
Masz ten moduł na stole to opowiadaj gdzie to ma ledy i który pin sobie podlutujesz pod reseta. 
Daj linka do moduły to posprawdzamy co z radiem.

**Comment by M0IGA** [comment]
Schemat T3
https://github.com/LilyGO/TTGO-LORA32/blob/master/schematic1in6.pdf

Tu piczer z opisem pinów i wygądem płytki https://imgur.com/Fnm4hQa

**Comment by SQ9MDD** [comment]
poprawione płytka działa
