### ISSUE TITLE
Display not working with Lora32 v2.1 version

### ISSUE THREAD

**Issue by mi-gri** [SQ9MDD/TTGO-T-Beam-LoRa-APRS#47]
Using the version for my Lora32 v2.1 board and the display keeps dark. I tried the Lora32 v2 version of the software instead and the display works.

**Comment by US1GHQ** [comment]
If you build from source, find this code in TTGO_T-Beam_LoRa_APRS.ino
`#elif LORA32_21
  #define I2C_SDA 4
  #define I2C_SCL 15
  #define BUTTON 2                  //pin number for BUTTO
  #define BUZZER 13                 // enter your buzzer pin gpio
  const byte TXLED  = 4;            //pin number for LED on TX Tracker
`
and change to
`#elif LORA32_21
  #define I2C_SDA 21
  #define I2C_SCL 22
  #define BUTTON 2                  //pin number for BUTTO
  #define BUZZER 13                 // enter your buzzer pin gpio
  const byte TXLED  = 4;            //pin number for LED on TX Tracker
`

**Comment by mi-gri** [comment]
Thank you - that worked for me.

**Comment by iu2frl** [comment]
is this a custom board or should we make it definitive?

**Comment by mi-gri** [comment]
I'm not sure if this is the default for the 2.1 versions, but I have now three boards, all need this change.

**Comment by iu2frl** [comment]
merged, we can close it
