### ISSUE TITLE
Display not working with T-Beam v1.1

### ISSUE THREAD

**Issue by mattbk** [SQ9MDD/TTGO-T-Beam-LoRa-APRS#50]
I looked at the pinouts and it looks like SDA = 21 and SCL = 22, even though the physical location of 21 and 22 switches between v1.0 and v1.1.

Is the screen not working because a v1.1 T-Beam is not being caught by the ifdef/elif in https://github.com/SQ9MDD/TTGO-T-Beam-LoRa-APRS/blob/master/src/TTGO_T-Beam_LoRa_APRS.ino?

I would try this myself, but I'm not even sure how to compile from source yet.

**Comment by SQ9MDD** [comment]
just ddisable dimmer via WWW.

**Comment by mattbk** [comment]
Thanks! Now that I know how to get to WWW interface (#49) I can do this.
