### ISSUE TITLE
TTGO T-Beam 0.7 voltage scaling problem

### ISSUE THREAD

**Issue by iu2frl** [SQ9MDD/TTGO-T-Beam-LoRa-APRS#65]
On TTGO T-BEAM battery at full charge is shown as 7.2V instead of 3.7

Using latest code (22 Aug) with T-Beam 0.7 binary

**Comment by iu2frl** [comment]
In "TTGO_T-Beam_LoRa_APRS.ino" file, line 359 change 4096 with 8192 like this:

`void batt_read(){
#ifdef T_BEAM_V1_0
  BattVolts = axp.getBattVoltage()/1000;
  InpVolts = axp.getVbusVoltage()/1000;
#else
  BattVolts = analogRead(35)*7.221/8192;
#endif
}`

**Comment by SQ9MDD** [comment]
corrected closed. Thanks Luca
