### ISSUE TITLE
Separate path for telemetry.

### ISSUE THREAD

**Issue by SQ9MDD** [SQ9MDD/TTGO-T-Beam-LoRa-APRS#77]
It is necessary to be able to set a path for telemetry to prevent this data from being repeated by the DIGI to which the TNC is connected.
Look at the screen below in DIGI I have two interfaces SQ9MDD-4 on 2m and SQ9MDD-3 LoRa. The telemetry from the Lora interface goes with the path as source data and is repeated on the 2m interface

![obraz](https://user-images.githubusercontent.com/5675191/133928403-709714c4-8e70-4f01-a088-c39d98272f72.png)

**Comment by mattbk** [comment]
Yes, I pulled that from #75 just so I could get something working, but it can be a new PR.
