### ISSUE TITLE
Blue blinking LED after Auto Power Off

### ISSUE THREAD

**Issue by mi-gri** [SQ9MDD/TTGO-T-Beam-LoRa-APRS#82]
Since one of the last updates, a blue LED flashes on my T-Beam 1.1 after Auto Shut Down. 
Is this supposed to be like that?

**Comment by mattbk** [comment]
Is it shut down, or just the screen turned off? A recent update turns the screen off after several seconds, and switched back on again with button press.

**Comment by mi-gri** [comment]
It is shut down following the auto shut down timer: It is not connectable and sends nothing out.

**Comment by SQ9MDD** [comment]
I think just before the command:
axp.shutdown();
still needs to be done:
axp.setChgLEDMode(AXP20X_LED_OFF);

**Comment by SQ9MDD** [comment]
I set the tracker to turn off automatically if the voltage is less than 3.3V while turning off 4Hz signaling. Let's see if this helps

**Comment by mi-gri** [comment]
Seems to work. Just added a pull request for the second shutdown code in taskWebServer.cpp

**Comment by SQ9MDD** [comment]
I hope this helped. I will close the ticket if there is a problem, we will reopen it
